package controlador;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//package com.mycompany.project;

import java.awt.event.ActionEvent;

import javax.swing.JOptionPane;

import modelo.OperacionesMilitares;
import vista.ActionListener;
import vista.ItemListener;
import vista.Teniente;

/**
 *
 * @author josue
 */
public class MostrarTeniente extends javax.swing.JFrame implements ActionListener, ItemListener, OperacionesMilitares{

    /**
     * Creates new form MostrarTeniente
     */
    public MostrarTeniente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMostrarTeniente = new javax.swing.JPanel();
        labelNameMostrarTeniente = new javax.swing.JLabel();
        textIDMostrarTeniente = new javax.swing.JTextField();
        labelIDMostrarTeniente = new javax.swing.JLabel();
        textNombreMostrarTeniente = new javax.swing.JTextField();
        labelNivelMostrarTeniente = new javax.swing.JLabel();
        textNivelMostrarTeniente = new javax.swing.JTextField();
        labelReporteMostrarTeniente = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaMisionMostrarTeniente = new javax.swing.JTextArea();
        labelMisionMostrarTeniente = new javax.swing.JLabel();
        labelAccionMostrarTeniente = new javax.swing.JLabel();
        textAccionMostrarTeniente = new javax.swing.JTextField();
        panelMostrarTeniente2 = new javax.swing.JPanel();
        labelMostrarTeniente = new javax.swing.JLabel();
        labelMostrarUnidades = new javax.swing.JLabel();
        textMostrarUnidades = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaReporteMostrarTeniente1 = new javax.swing.JTextArea();
        botonMostrarTeniente = new javax.swing.JButton();
        botonResetMostrarTeniente = new javax.swing.JButton();
        panelBuscadorTeniente = new javax.swing.JPanel();
        textBuscadorTeniente = new javax.swing.JTextField();
        textBuscarTeniente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelMostrarTeniente.setBackground(new java.awt.Color(19, 71, 89));

        labelNameMostrarTeniente.setForeground(new java.awt.Color(255, 255, 255));
        labelNameMostrarTeniente.setText("Nombre");

        textIDMostrarTeniente.setEditable(false);

        labelIDMostrarTeniente.setForeground(new java.awt.Color(255, 255, 255));
        labelIDMostrarTeniente.setText("ID");

        textNombreMostrarTeniente.setEditable(false);
        textNombreMostrarTeniente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombreMostrarTenienteActionPerformed(evt);
            }
        });

        labelNivelMostrarTeniente.setForeground(new java.awt.Color(255, 255, 255));
        labelNivelMostrarTeniente.setText("Nivel");

        textNivelMostrarTeniente.setEditable(false);

        labelReporteMostrarTeniente.setForeground(new java.awt.Color(255, 255, 255));
        labelReporteMostrarTeniente.setText("Reporte");

        areaMisionMostrarTeniente.setEditable(false);
        areaMisionMostrarTeniente.setColumns(20);
        areaMisionMostrarTeniente.setRows(5);
        jScrollPane1.setViewportView(areaMisionMostrarTeniente);

        labelMisionMostrarTeniente.setForeground(new java.awt.Color(255, 255, 255));
        labelMisionMostrarTeniente.setText("Misión");

        labelAccionMostrarTeniente.setForeground(new java.awt.Color(255, 255, 255));
        labelAccionMostrarTeniente.setText("Acción");

        textAccionMostrarTeniente.setEditable(false);

        panelMostrarTeniente2.setBackground(new java.awt.Color(0, 153, 153));

        labelMostrarTeniente.setBackground(new java.awt.Color(0, 153, 153));
        labelMostrarTeniente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelMostrarTeniente.setForeground(new java.awt.Color(255, 255, 255));
        labelMostrarTeniente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMostrarTeniente.setText("Mostrar Teniente");

        javax.swing.GroupLayout panelMostrarTeniente2Layout = new javax.swing.GroupLayout(panelMostrarTeniente2);
        panelMostrarTeniente2.setLayout(panelMostrarTeniente2Layout);
        panelMostrarTeniente2Layout.setHorizontalGroup(
            panelMostrarTeniente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMostrarTeniente2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMostrarTeniente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelMostrarTeniente2Layout.setVerticalGroup(
            panelMostrarTeniente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMostrarTeniente2Layout.createSequentialGroup()
                .addComponent(labelMostrarTeniente, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        labelMostrarUnidades.setForeground(new java.awt.Color(255, 255, 255));
        labelMostrarUnidades.setText("Unidades de las que se hace cargo");

        textMostrarUnidades.setEditable(false);

        areaReporteMostrarTeniente1.setEditable(false);
        areaReporteMostrarTeniente1.setColumns(20);
        areaReporteMostrarTeniente1.setRows(5);
        jScrollPane3.setViewportView(areaReporteMostrarTeniente1);

        botonMostrarTeniente.setBackground(new java.awt.Color(0, 153, 153));
        botonMostrarTeniente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonMostrarTeniente.setText("Mostrar");
        botonMostrarTeniente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarTenienteActionPerformed(evt);
            }
        });


        botonResetMostrarTeniente.setBackground(new java.awt.Color(0, 153, 153));
        botonResetMostrarTeniente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonResetMostrarTeniente.setText("Reset");
        botonResetMostrarTeniente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonResetMostrarTenienteActionPerformed(evt);
            }
        });


        javax.swing.GroupLayout panelMostrarTenienteLayout = new javax.swing.GroupLayout(panelMostrarTeniente);
        panelMostrarTeniente.setLayout(panelMostrarTenienteLayout);
        panelMostrarTenienteLayout.setHorizontalGroup(
            panelMostrarTenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMostrarTeniente2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelMostrarTenienteLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(panelMostrarTenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMostrarTenienteLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelMostrarTenienteLayout.createSequentialGroup()
                        .addComponent(labelMisionMostrarTeniente)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMostrarTenienteLayout.createSequentialGroup()
                        .addGroup(panelMostrarTenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelMostrarTenienteLayout.createSequentialGroup()
                                .addComponent(botonResetMostrarTeniente, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonMostrarTeniente, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelMostrarTenienteLayout.createSequentialGroup()
                                .addGroup(panelMostrarTenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textIDMostrarTeniente, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textNombreMostrarTeniente, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelIDMostrarTeniente)
                                    .addComponent(labelNivelMostrarTeniente)
                                    .addComponent(labelNameMostrarTeniente)
                                    .addComponent(textNivelMostrarTeniente, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelAccionMostrarTeniente)
                                    .addComponent(textAccionMostrarTeniente, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                                .addGroup(panelMostrarTenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelReporteMostrarTeniente)
                                    .addComponent(labelMostrarUnidades)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textMostrarUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(43, 43, 43))))
        );
        panelMostrarTenienteLayout.setVerticalGroup(
            panelMostrarTenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMostrarTenienteLayout.createSequentialGroup()
                .addComponent(panelMostrarTeniente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(panelMostrarTenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNameMostrarTeniente)
                    .addComponent(labelReporteMostrarTeniente))
                .addGap(12, 12, 12)
                .addGroup(panelMostrarTenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMostrarTenienteLayout.createSequentialGroup()
                        .addComponent(textNombreMostrarTeniente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelIDMostrarTeniente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textIDMostrarTeniente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelMostrarTenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNivelMostrarTeniente)
                    .addComponent(labelMostrarUnidades))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelMostrarTenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNivelMostrarTeniente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textMostrarUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelAccionMostrarTeniente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textAccionMostrarTeniente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelMisionMostrarTeniente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(panelMostrarTenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonMostrarTeniente)
                    .addComponent(botonResetMostrarTeniente))
                .addGap(41, 41, 41))
        );

        panelBuscadorTeniente.setBackground(new java.awt.Color(0, 153, 153));

        textBuscarTeniente.setForeground(new java.awt.Color(255, 255, 255));
        textBuscarTeniente.setText("Buscar ID");

        javax.swing.GroupLayout panelBuscadorTenienteLayout = new javax.swing.GroupLayout(panelBuscadorTeniente);
        panelBuscadorTeniente.setLayout(panelBuscadorTenienteLayout);
        panelBuscadorTenienteLayout.setHorizontalGroup(
            panelBuscadorTenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBuscadorTenienteLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(panelBuscadorTenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textBuscarTeniente)
                    .addComponent(textBuscadorTeniente, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        panelBuscadorTenienteLayout.setVerticalGroup(
            panelBuscadorTenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscadorTenienteLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(textBuscarTeniente)
                .addGap(18, 18, 18)
                .addComponent(textBuscadorTeniente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelBuscadorTeniente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelMostrarTeniente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMostrarTeniente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelBuscadorTeniente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNombreMostrarTenienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreMostrarTenienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNombreMostrarTenienteActionPerformed

    private void botonResetMostrarTenienteActionPerformed(ActionEvent evt) {
        textNombreMostrarTeniente.setText("");
        textIDMostrarTeniente.setText("");
        textNivelMostrarTeniente.setText("");
        textAccionMostrarTeniente.setText("");
        areaMisionMostrarTeniente.setText("");
        areaReporteMostrarTeniente1.setText("");
        textMostrarUnidades.setText("");
    }
    
    private void botonMostrarTenienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBuscadorTenienteActionPerformed
        String buscador;

        buscador=textBuscadorTeniente.getText();

        System.out.println(buscador);

        textBuscadorTeniente.setText("");

        //////////////////////
        //MOSTRARINFORMACION//
        //////////////////////

            Boolean encontrado = false;
            int contador = 0;
            //Siclo para recorrer la lista
            for (Teniente Teniente : listaTeniente) {

                System.out.println(listaTeniente.size());
                //Condicion para verificar si el Teniente existe comparando con los datos ingresados
                if(buscador.equals(Teniente.id)){
                    
                    
                    //Si se cumple muestra lo siguiente
                    textNombreMostrarTeniente.setText(Teniente.nombre);
                    textIDMostrarTeniente.setText(Teniente.id);
                    textNivelMostrarTeniente.setText(Teniente.nivel);
                    textAccionMostrarTeniente.setText(accionTeniente.get(contador));
                    areaMisionMostrarTeniente.setText(Teniente.mision);
                    areaReporteMostrarTeniente1.setText(Teniente.reporte);
                    textMostrarUnidades.setText(Teniente.reporte);

                    System.out.println("x");

                    //Si el Teniente fue encontrado la varieable se actualiza
                    encontrado = true;
                    break;
                }else{
                    contador ++;
                }
            }
            
            //Si el Teniente no fue encontrado se muestra este mensaje
            if (encontrado == false) {
                JOptionPane.showMessageDialog(null, "No se encontró el Teniente", "Información Teniente", JOptionPane.ERROR_MESSAGE);
            }

    }//GEN-LAST:event_textBuscadorTenienteActionPerformed



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarTeniente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarTeniente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarTeniente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarTeniente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarTeniente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaMisionMostrarTeniente;
    private javax.swing.JTextArea areaReporteMostrarTeniente1;
    private javax.swing.JButton botonMostrarTeniente;
    private javax.swing.JButton botonResetMostrarTeniente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelAccionMostrarTeniente;
    private javax.swing.JLabel labelIDMostrarTeniente;
    private javax.swing.JLabel labelMisionMostrarTeniente;
    private javax.swing.JLabel labelMostrarTeniente;
    private javax.swing.JLabel labelMostrarUnidades;
    private javax.swing.JLabel labelNameMostrarTeniente;
    private javax.swing.JLabel labelNivelMostrarTeniente;
    private javax.swing.JLabel labelReporteMostrarTeniente;
    private javax.swing.JPanel panelBuscadorTeniente;
    private javax.swing.JPanel panelMostrarTeniente;
    private javax.swing.JPanel panelMostrarTeniente2;
    private javax.swing.JTextField textAccionMostrarTeniente;
    private javax.swing.JTextField textBuscadorTeniente;
    private javax.swing.JLabel textBuscarTeniente;
    private javax.swing.JTextField textIDMostrarTeniente;
    private javax.swing.JTextField textMostrarUnidades;
    private javax.swing.JTextField textNivelMostrarTeniente;
    private javax.swing.JTextField textNombreMostrarTeniente;
    // End of variables declaration//GEN-END:variables
    @Override
    public void crearSoldado() {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'crearSoldado'");
    }

    @Override
    public void mostrarInformacion() {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'mostrarInformacion'");
    }

    @Override
    public void modificarSoldado() {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'modificarSoldado'");
    }

    @Override
    public void asignarMision(String mision) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'asignarMision'");
    }

    @Override
    public void reportarEstado() {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'reportarEstado'");
    }
}
