package controlador;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//package com.mycompany.project;

import java.awt.event.ActionEvent;

import javax.swing.JOptionPane;

import modelo.OperacionesMilitares;
import vista.ActionListener;
import vista.Capitan;
import vista.ItemListener;

/**
 *
 * @author josue
 */
public class MostrarCapitan extends javax.swing.JFrame implements ActionListener, ItemListener, OperacionesMilitares{

    /**
     * Creates new form MostrarCapitan
     */
    public MostrarCapitan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMostrarCapitan = new javax.swing.JPanel();
        labelNameMostrarCapitan = new javax.swing.JLabel();
        textIDMostrarCapitan = new javax.swing.JTextField();
        labelIDMostrarCapitan = new javax.swing.JLabel();
        textNombreMostrarCapitan = new javax.swing.JTextField();
        labelNivelMostrarCapitan = new javax.swing.JLabel();
        textNivelMostrarCapitan = new javax.swing.JTextField();
        labelReporteMostrarCapitan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaMisionMostrarCapitan = new javax.swing.JTextArea();
        labelMisionMostrarCapitan = new javax.swing.JLabel();
        labelAccionMostrarCapitan = new javax.swing.JLabel();
        textAccionMostrarCapitan = new javax.swing.JTextField();
        panelMostrarCapitan2 = new javax.swing.JPanel();
        labelMostrarCapitan = new javax.swing.JLabel();
        labelEstrategia = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaReporteEstrategiarCapitan = new javax.swing.JTextArea();
        botonResetMostrarCapitan = new javax.swing.JButton();
        botonMostrarCapitan = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        areaReporteMostrarCapitan1 = new javax.swing.JTextArea();
        panelBuscadorCapitan = new javax.swing.JPanel();
        textBuscadorCapitan = new javax.swing.JTextField();
        textBuscarCapitan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelMostrarCapitan.setBackground(new java.awt.Color(19, 71, 89));

        labelNameMostrarCapitan.setForeground(new java.awt.Color(255, 255, 255));
        labelNameMostrarCapitan.setText("Nombre");

        textIDMostrarCapitan.setEditable(false);
        textIDMostrarCapitan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIDMostrarCapitanActionPerformed(evt);
            }
        });

        labelIDMostrarCapitan.setForeground(new java.awt.Color(255, 255, 255));
        labelIDMostrarCapitan.setText("ID");

        textNombreMostrarCapitan.setEditable(false);
        textNombreMostrarCapitan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombreMostrarCapitanActionPerformed(evt);
            }
        });

        labelNivelMostrarCapitan.setForeground(new java.awt.Color(255, 255, 255));
        labelNivelMostrarCapitan.setText("Nivel");

        textNivelMostrarCapitan.setEditable(false);

        labelReporteMostrarCapitan.setForeground(new java.awt.Color(255, 255, 255));
        labelReporteMostrarCapitan.setText("Reporte");

        areaMisionMostrarCapitan.setEditable(false);
        areaMisionMostrarCapitan.setColumns(20);
        areaMisionMostrarCapitan.setRows(5);
        jScrollPane1.setViewportView(areaMisionMostrarCapitan);

        labelMisionMostrarCapitan.setForeground(new java.awt.Color(255, 255, 255));
        labelMisionMostrarCapitan.setText("Misión");

        labelAccionMostrarCapitan.setForeground(new java.awt.Color(255, 255, 255));
        labelAccionMostrarCapitan.setText("Acción");

        textAccionMostrarCapitan.setEditable(false);

        panelMostrarCapitan2.setBackground(new java.awt.Color(0, 153, 153));

        labelMostrarCapitan.setBackground(new java.awt.Color(0, 153, 153));
        labelMostrarCapitan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelMostrarCapitan.setForeground(new java.awt.Color(255, 255, 255));
        labelMostrarCapitan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMostrarCapitan.setText("Mostrar Capitan");

        javax.swing.GroupLayout panelMostrarCapitan2Layout = new javax.swing.GroupLayout(panelMostrarCapitan2);
        panelMostrarCapitan2.setLayout(panelMostrarCapitan2Layout);
        panelMostrarCapitan2Layout.setHorizontalGroup(
            panelMostrarCapitan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMostrarCapitan2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMostrarCapitan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelMostrarCapitan2Layout.setVerticalGroup(
            panelMostrarCapitan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMostrarCapitan2Layout.createSequentialGroup()
                .addComponent(labelMostrarCapitan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        labelEstrategia.setForeground(new java.awt.Color(255, 255, 255));
        labelEstrategia.setText("Estrategia");

        areaReporteEstrategiarCapitan.setEditable(false);
        areaReporteEstrategiarCapitan.setColumns(20);
        areaReporteEstrategiarCapitan.setRows(5);
        jScrollPane3.setViewportView(areaReporteEstrategiarCapitan);

        botonResetMostrarCapitan.setBackground(new java.awt.Color(0, 153, 153));
        botonResetMostrarCapitan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonResetMostrarCapitan.setText("Reset");
        botonResetMostrarCapitan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonResetMostrarCapitanActionPerformed(evt);
            }
        });

        botonMostrarCapitan.setBackground(new java.awt.Color(0, 153, 153));
        botonMostrarCapitan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonMostrarCapitan.setText("Mostrar");
        botonMostrarCapitan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarCapitanActionPerformed(evt);
            }
        });

        areaReporteMostrarCapitan1.setEditable(false);
        areaReporteMostrarCapitan1.setColumns(20);
        areaReporteMostrarCapitan1.setRows(5);
        jScrollPane4.setViewportView(areaReporteMostrarCapitan1);

        javax.swing.GroupLayout panelMostrarCapitanLayout = new javax.swing.GroupLayout(panelMostrarCapitan);
        panelMostrarCapitan.setLayout(panelMostrarCapitanLayout);
        panelMostrarCapitanLayout.setHorizontalGroup(
            panelMostrarCapitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMostrarCapitan2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelMostrarCapitanLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(panelMostrarCapitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMostrarCapitanLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelMostrarCapitanLayout.createSequentialGroup()
                        .addComponent(labelMisionMostrarCapitan)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelMostrarCapitanLayout.createSequentialGroup()
                        .addGroup(panelMostrarCapitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMostrarCapitanLayout.createSequentialGroup()
                                .addComponent(botonResetMostrarCapitan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonMostrarCapitan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelMostrarCapitanLayout.createSequentialGroup()
                                .addGroup(panelMostrarCapitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textIDMostrarCapitan, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textNombreMostrarCapitan, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelIDMostrarCapitan)
                                    .addComponent(labelNivelMostrarCapitan)
                                    .addComponent(labelNameMostrarCapitan)
                                    .addComponent(textNivelMostrarCapitan, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelAccionMostrarCapitan)
                                    .addComponent(textAccionMostrarCapitan, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                                .addGroup(panelMostrarCapitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelReporteMostrarCapitan)
                                    .addComponent(labelEstrategia)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(43, 43, 43))))
        );
        panelMostrarCapitanLayout.setVerticalGroup(
            panelMostrarCapitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMostrarCapitanLayout.createSequentialGroup()
                .addComponent(panelMostrarCapitan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(panelMostrarCapitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNameMostrarCapitan)
                    .addComponent(labelReporteMostrarCapitan))
                .addGap(12, 12, 12)
                .addGroup(panelMostrarCapitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMostrarCapitanLayout.createSequentialGroup()
                        .addComponent(textNombreMostrarCapitan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelIDMostrarCapitan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textIDMostrarCapitan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelMostrarCapitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNivelMostrarCapitan)
                    .addComponent(labelEstrategia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelMostrarCapitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMostrarCapitanLayout.createSequentialGroup()
                        .addComponent(textNivelMostrarCapitan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelAccionMostrarCapitan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textAccionMostrarCapitan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelMisionMostrarCapitan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(panelMostrarCapitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonResetMostrarCapitan)
                    .addComponent(botonMostrarCapitan))
                .addGap(41, 41, 41))
        );

        panelBuscadorCapitan.setBackground(new java.awt.Color(0, 153, 153));

        textBuscadorCapitan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBuscadorCapitanActionPerformed(evt);
            }
        });

        textBuscarCapitan.setForeground(new java.awt.Color(255, 255, 255));
        textBuscarCapitan.setText("Buscar ID");

        javax.swing.GroupLayout panelBuscadorCapitanLayout = new javax.swing.GroupLayout(panelBuscadorCapitan);
        panelBuscadorCapitan.setLayout(panelBuscadorCapitanLayout);
        panelBuscadorCapitanLayout.setHorizontalGroup(
            panelBuscadorCapitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBuscadorCapitanLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(panelBuscadorCapitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textBuscarCapitan)
                    .addComponent(textBuscadorCapitan, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        panelBuscadorCapitanLayout.setVerticalGroup(
            panelBuscadorCapitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscadorCapitanLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(textBuscarCapitan)
                .addGap(18, 18, 18)
                .addComponent(textBuscadorCapitan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelBuscadorCapitan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelMostrarCapitan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMostrarCapitan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(panelBuscadorCapitan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNombreMostrarCapitanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreMostrarCapitanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNombreMostrarCapitanActionPerformed

    private void textIDMostrarCapitanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIDMostrarCapitanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIDMostrarCapitanActionPerformed

    private void textBuscadorCapitanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBuscadorCapitanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBuscadorCapitanActionPerformed

    private void botonResetMostrarCapitanActionPerformed(ActionEvent evt) {
        textNombreMostrarCapitan.setText("");
        textIDMostrarCapitan.setText("");
        textNivelMostrarCapitan.setText("");
        textAccionMostrarCapitan.setText("");
        areaMisionMostrarCapitan.setText("");
        areaReporteMostrarCapitan1.setText("");
        areaReporteEstrategiarCapitan.setText("");
    }



    private void botonMostrarCapitanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarCapitanActionPerformed
           String buscador;

        buscador=textBuscadorCapitan.getText();

        System.out.println(buscador);

        textBuscadorCapitan.setText("");

        //////////////////////
        //MOSTRARINFORMACION//
        //////////////////////

            Boolean encontrado = false;
            int contador = 0;
            //Siclo para recorrer la lista
            for (Capitan Capitan : listaCapitan) {

                System.out.println(listaCapitan.size());
                //Condicion para verificar si el Capitan existe comparando con los datos ingresados
                if(buscador.equals(Capitan.id)){
                    
                    
                    //Si se cumple muestra lo siguiente
                    textNombreMostrarCapitan.setText(Capitan.nombre);
                    textIDMostrarCapitan.setText(Capitan.id);
                    textNivelMostrarCapitan.setText(Capitan.nivel);
                    textAccionMostrarCapitan.setText(accionCapitan.get(contador));
                    areaMisionMostrarCapitan.setText(Capitan.mision);
                    areaReporteMostrarCapitan1.setText(Capitan.reporte);
                    areaReporteEstrategiarCapitan.setText(Capitan.estrategia);

                    System.out.println("x");

                    //Si el Capitan fue encontrado la varieable se actualiza
                    encontrado = true;
                    break;
                }else{
                    contador ++;
                }
            }
            
            //Si el Capitan no fue encontrado se muestra este mensaje
            if (encontrado == false) {
                JOptionPane.showMessageDialog(null, "No se encontró el Capitan", "Información Capitan", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_botonMostrarCapitanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarCapitan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarCapitan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarCapitan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarCapitan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarCapitan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaMisionMostrarCapitan;
    private javax.swing.JTextArea areaReporteEstrategiarCapitan;
    private javax.swing.JTextArea areaReporteMostrarCapitan1;
    private javax.swing.JButton botonMostrarCapitan;
    private javax.swing.JButton botonResetMostrarCapitan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelAccionMostrarCapitan;
    private javax.swing.JLabel labelEstrategia;
    private javax.swing.JLabel labelIDMostrarCapitan;
    private javax.swing.JLabel labelMisionMostrarCapitan;
    private javax.swing.JLabel labelMostrarCapitan;
    private javax.swing.JLabel labelNameMostrarCapitan;
    private javax.swing.JLabel labelNivelMostrarCapitan;
    private javax.swing.JLabel labelReporteMostrarCapitan;
    private javax.swing.JPanel panelBuscadorCapitan;
    private javax.swing.JPanel panelMostrarCapitan;
    private javax.swing.JPanel panelMostrarCapitan2;
    private javax.swing.JTextField textAccionMostrarCapitan;
    private javax.swing.JTextField textBuscadorCapitan;
    private javax.swing.JLabel textBuscarCapitan;
    private javax.swing.JTextField textIDMostrarCapitan;
    private javax.swing.JTextField textNivelMostrarCapitan;
    private javax.swing.JTextField textNombreMostrarCapitan;
    // End of variables declaration//GEN-END:variables
    @Override
    public void crearSoldado() {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'crearSoldado'");
    }

    @Override
    public void mostrarInformacion() {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'mostrarInformacion'");
    }

    @Override
    public void modificarSoldado() {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'modificarSoldado'");
    }

    @Override
    public void asignarMision(String mision) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'asignarMision'");
    }

    @Override
    public void reportarEstado() {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'reportarEstado'");
    }
}
