package vista;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//package com.mycompany.project;

import javax.swing.ButtonGroup;

import controlador.OperacionesMilitares;

/**
 *
 * @author josue
 */
public class MenuRangosModificar extends javax.swing.JFrame implements ActionListener, ItemListener, OperacionesMilitares{

    /**
     * Creates new form MenuRangosModificar
     */
    public MenuRangosModificar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelRangosModificar = new javax.swing.JPanel();
        panelRangosModificar = new javax.swing.JPanel();
        labelRangosModificar = new javax.swing.JLabel();
        radioSoldadoRasoModificar = new javax.swing.JRadioButton();
        radioTenienteModificar = new javax.swing.JRadioButton();
        radioCoronelModificar = new javax.swing.JRadioButton();
        radioCapitanModificar = new javax.swing.JRadioButton();
        botonRangosModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PanelRangosModificar.setBackground(new java.awt.Color(19, 71, 89));

        panelRangosModificar.setBackground(new java.awt.Color(0, 153, 153));

        labelRangosModificar.setBackground(new java.awt.Color(0, 153, 153));
        labelRangosModificar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelRangosModificar.setForeground(new java.awt.Color(255, 255, 255));
        labelRangosModificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRangosModificar.setText("Seleccionar Rango");

        javax.swing.GroupLayout panelRangosModificarLayout = new javax.swing.GroupLayout(panelRangosModificar);
        panelRangosModificar.setLayout(panelRangosModificarLayout);
        panelRangosModificarLayout.setHorizontalGroup(
            panelRangosModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRangosModificarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelRangosModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRangosModificarLayout.setVerticalGroup(
            panelRangosModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelRangosModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        radioSoldadoRasoModificar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radioSoldadoRasoModificar.setForeground(new java.awt.Color(255, 255, 255));
        radioSoldadoRasoModificar.setText("\tSoldadoRaso");
        // radioSoldadoRasoModificar.addActionListener(new java.awt.event.ActionListener() {
        //     public void actionPerformed(java.awt.event.ActionEvent evt) {
        //         radioSoldadoRasoModificarActionPerformed(evt);
        //     }
        // });

        radioTenienteModificar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radioTenienteModificar.setForeground(new java.awt.Color(255, 255, 255));
        radioTenienteModificar.setText("Teniente");
        // radioTenienteModificar.addActionListener(new java.awt.event.ActionListener() {
        //     public void actionPerformed(java.awt.event.ActionEvent evt) {
        //         radioTenienteModificarActionPerformed(evt);
        //     }
        // });

        radioCoronelModificar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radioCoronelModificar.setForeground(new java.awt.Color(255, 255, 255));
        radioCoronelModificar.setText("Coronel");

        radioCapitanModificar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radioCapitanModificar.setForeground(new java.awt.Color(255, 255, 255));
        radioCapitanModificar.setText("Capitan");

        botonRangosModificar.setBackground(new java.awt.Color(0, 153, 153));
        botonRangosModificar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonRangosModificar.setText("Next");
        botonRangosModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRangosModificarActionPerformed(evt);
                if (radioSoldadoRasoModificar.isSelected()) {
                    ModificarSoldadoRaso modificar=new ModificarSoldadoRaso();
                    modificar.setVisible(true);                       
               } else if (radioCapitanModificar.isSelected()) {
                    ModificarCapitan modificar = new ModificarCapitan();
                    modificar.setVisible(true);
                  
                } else if (radioCoronelModificar.isSelected()) {
                    ModificarCoronel modificar= new ModificarCoronel();
                    modificar.setVisible(true);
                   
                } else if (radioTenienteModificar.isSelected()) {
                    ModificarTeniente modificar = new ModificarTeniente();
                    modificar.setVisible(true);
                    
                }
            }
            
        });
        ButtonGroup grupo = new ButtonGroup();
        grupo.add(radioSoldadoRasoModificar);
        grupo.add(radioTenienteModificar);
        grupo.add(radioCoronelModificar);
        grupo.add(radioCapitanModificar);


        javax.swing.GroupLayout PanelRangosModificarLayout = new javax.swing.GroupLayout(PanelRangosModificar);
        PanelRangosModificar.setLayout(PanelRangosModificarLayout);
        PanelRangosModificarLayout.setHorizontalGroup(
            PanelRangosModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRangosModificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelRangosModificarLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(PanelRangosModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(radioCapitanModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radioCoronelModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radioTenienteModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radioSoldadoRasoModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonRangosModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        PanelRangosModificarLayout.setVerticalGroup(
            PanelRangosModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRangosModificarLayout.createSequentialGroup()
                .addComponent(panelRangosModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(radioSoldadoRasoModificar)
                .addGap(18, 18, 18)
                .addComponent(radioTenienteModificar)
                .addGap(30, 30, 30)
                .addComponent(radioCoronelModificar)
                .addGap(30, 30, 30)
                .addComponent(radioCapitanModificar)
                .addGap(30, 30, 30)
                .addComponent(botonRangosModificar)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelRangosModificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelRangosModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();

         


    }// </editor-fold>//GEN-END:initComponents

    // private void radioSoldadoRasoModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSoldadoRasoModificarActionPerformed
        
    //     ButtonGroup group = new ButtonGroup();
        
    //     CrearSoldadoRaso nuevoSoldadoRaso = new CrearSoldadoRaso();
    //     nuevoSoldadoRaso.setVisible(true);     
    //     group.add(radioSoldadoRasoModificar);
    // }//GEN-LAST:event_radioSoldadoRasoModificarActionPerformed

    // private void radioTenienteModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTenienteModificarActionPerformed
    //     ButtonGroup group = new ButtonGroup();
    //     CrearTeniente nuevoTeniente = new CrearTeniente();
    //     nuevoTeniente.setVisible(true);
    //     group.add(radioTenienteModificar);
    // }//GEN-LAST:event_radioTenienteModificarActionPerformed

    // private void radioCoronelModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTenienteModificarActionPerformed
    //     ButtonGroup group = new ButtonGroup();
    //     CrearCoronel nuevoCoronel = new CrearCoronel();
    //     nuevoCoronel.setVisible(rootPaneCheckingEnabled);;
    //     group.add(radioCoronelModificar);
    // }//GEN-LAST:event_radioTenienteModificarActionPerformed

    // private void radioCapitanModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTenienteModificarActionPerformed
    //     ButtonGroup group = new ButtonGroup();
    //     crearCapitan nuevoCapitan = new crearCapitan();
    //     nuevoCapitan.setVisible(true);
    //     group.add(radioCapitanModificar);
    // }//GEN-LAST:event_radioTenienteModificarActionPerformed

    private void botonRangosModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRangosModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRangosModificarActionPerformed

    
    
    
   
    


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuRangosModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuRangosModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuRangosModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuRangosModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuRangosModificar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelRangosModificar;
    private javax.swing.JButton botonRangosModificar;
    private javax.swing.JLabel labelRangosModificar;
    private javax.swing.JPanel panelRangosModificar;
    private javax.swing.JRadioButton radioCapitanModificar;
    private javax.swing.JRadioButton radioCoronelModificar;
    private javax.swing.JRadioButton radioSoldadoRasoModificar;
    private javax.swing.JRadioButton radioTenienteModificar;
    // End of variables declaration//GEN-END:variables
    @Override
    public void crearSoldado() {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'crearSoldado'");
    }

    @Override
    public void mostrarInformacion() {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'mostrarInformacion'");
    }

    @Override
    public void modificarSoldado() {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'modificarSoldado'");
    }

    @Override
    public void asignarMision(String mision) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'asignarMision'");
    }

    @Override
    public void reportarEstado() {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'reportarEstado'");
    }
}
