package vista;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//package com.mycompany.project;

import javax.swing.JOptionPane;

import controlador.OperacionesMilitares;

/**
 *
 * @author josue
 */
public class ModificarTeniente extends javax.swing.JFrame implements ActionListener, ItemListener, OperacionesMilitares{

    /**
     * Creates new form CrearTeniente
     */
    public ModificarTeniente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        JOptionPane.showMessageDialog(null,"Use enter en el buscador para realizar su busqueda");
        panelBuscadorModificarTeniente = new javax.swing.JPanel();
        textBuscadorModificarTeniente = new javax.swing.JTextField();
        textBuscarModificarTeniente = new javax.swing.JLabel();
        panelModificarTeniente = new javax.swing.JPanel();
        labelNameModificarTeniente = new javax.swing.JLabel();
        textNombreModificarTeniente = new javax.swing.JTextField();
        labelNivelModificarTeniente = new javax.swing.JLabel();
        textNivelModificarTeniente = new javax.swing.JTextField();
        labelReporteModificarTeniente = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaMisionModificarTeniente = new javax.swing.JTextArea();
        labelMisionModificarTeniente = new javax.swing.JLabel();
        labelAccionModificarTeniente = new javax.swing.JLabel();
        textAccionModificarTeniente = new javax.swing.JTextField();
        panelModificarTeniente2 = new javax.swing.JPanel();
        labelModificarTeniente = new javax.swing.JLabel();
        labelModificarUnidades = new javax.swing.JLabel();
        textModificarUnidades = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaReporteModificarTeniente1 = new javax.swing.JTextArea();
        botonModificarTeniente = new javax.swing.JButton();
        botonResetModificarTeniente = new javax.swing.JButton();
        botonEliminarTeniente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelBuscadorModificarTeniente.setBackground(new java.awt.Color(0, 153, 153));

        textBuscadorModificarTeniente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBuscadorModificarTenienteActionPerformed(evt);
            }
        });

        textBuscarModificarTeniente.setForeground(new java.awt.Color(255, 255, 255));
        textBuscarModificarTeniente.setText("Buscar ID");

        javax.swing.GroupLayout panelBuscadorModificarTenienteLayout = new javax.swing.GroupLayout(panelBuscadorModificarTeniente);
        panelBuscadorModificarTeniente.setLayout(panelBuscadorModificarTenienteLayout);
        panelBuscadorModificarTenienteLayout.setHorizontalGroup(
            panelBuscadorModificarTenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBuscadorModificarTenienteLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(panelBuscadorModificarTenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textBuscarModificarTeniente)
                    .addComponent(textBuscadorModificarTeniente, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        panelBuscadorModificarTenienteLayout.setVerticalGroup(
            panelBuscadorModificarTenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscadorModificarTenienteLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(textBuscarModificarTeniente)
                .addGap(18, 18, 18)
                .addComponent(textBuscadorModificarTeniente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelModificarTeniente.setBackground(new java.awt.Color(19, 71, 89));

        labelNameModificarTeniente.setForeground(new java.awt.Color(255, 255, 255));
        labelNameModificarTeniente.setText("Nombre");


        labelNivelModificarTeniente.setForeground(new java.awt.Color(255, 255, 255));
        labelNivelModificarTeniente.setText("Nivel");

        labelReporteModificarTeniente.setForeground(new java.awt.Color(255, 255, 255));
        labelReporteModificarTeniente.setText("Reporte");

        areaMisionModificarTeniente.setColumns(20);
        areaMisionModificarTeniente.setRows(5);
        jScrollPane1.setViewportView(areaMisionModificarTeniente);

        labelMisionModificarTeniente.setForeground(new java.awt.Color(255, 255, 255));
        labelMisionModificarTeniente.setText("Misión");

        labelAccionModificarTeniente.setForeground(new java.awt.Color(255, 255, 255));
        labelAccionModificarTeniente.setText("Acción");

        panelModificarTeniente2.setBackground(new java.awt.Color(0, 153, 153));

        labelModificarTeniente.setBackground(new java.awt.Color(0, 153, 153));
        labelModificarTeniente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelModificarTeniente.setForeground(new java.awt.Color(255, 255, 255));
        labelModificarTeniente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelModificarTeniente.setText("Modificar Teniente");

        javax.swing.GroupLayout panelModificarTeniente2Layout = new javax.swing.GroupLayout(panelModificarTeniente2);
        panelModificarTeniente2.setLayout(panelModificarTeniente2Layout);
        panelModificarTeniente2Layout.setHorizontalGroup(
            panelModificarTeniente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelModificarTeniente2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelModificarTeniente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelModificarTeniente2Layout.setVerticalGroup(
            panelModificarTeniente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarTeniente2Layout.createSequentialGroup()
                .addComponent(labelModificarTeniente, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        labelModificarUnidades.setForeground(new java.awt.Color(255, 255, 255));
        labelModificarUnidades.setText("Unidades de las que se hace cargo");

        areaReporteModificarTeniente1.setColumns(20);
        areaReporteModificarTeniente1.setRows(5);
        jScrollPane3.setViewportView(areaReporteModificarTeniente1);

        botonModificarTeniente.setBackground(new java.awt.Color(0, 153, 153));
        botonModificarTeniente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonModificarTeniente.setText("Modificar");
        botonModificarTeniente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarTenienteActionPerformed(evt);
            }
        });

        botonResetModificarTeniente.setBackground(new java.awt.Color(0, 153, 153));
        botonResetModificarTeniente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonResetModificarTeniente.setText("Reset");
        botonResetModificarTeniente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonResetModificarTenienteActionPerformed(evt);
            }
        });

        botonEliminarTeniente.setBackground(new java.awt.Color(0, 153, 153));
        botonEliminarTeniente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonEliminarTeniente.setText("Eliminar");
        botonEliminarTeniente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarTenienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelModificarTenienteLayout = new javax.swing.GroupLayout(panelModificarTeniente);
        panelModificarTeniente.setLayout(panelModificarTenienteLayout);
        panelModificarTenienteLayout.setHorizontalGroup(
            panelModificarTenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelModificarTeniente2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelModificarTenienteLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(panelModificarTenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelModificarTenienteLayout.createSequentialGroup()
                        .addComponent(labelMisionModificarTeniente)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelModificarTenienteLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelModificarTenienteLayout.createSequentialGroup()
                        .addGroup(panelModificarTenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelModificarTenienteLayout.createSequentialGroup()
                                .addComponent(botonResetModificarTeniente, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                                .addComponent(botonEliminarTeniente, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(94, 94, 94)
                                .addComponent(botonModificarTeniente, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelModificarTenienteLayout.createSequentialGroup()
                                .addGroup(panelModificarTenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textNombreModificarTeniente, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelNivelModificarTeniente)
                                    .addComponent(labelNameModificarTeniente)
                                    .addComponent(textNivelModificarTeniente, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelAccionModificarTeniente)
                                    .addComponent(textAccionModificarTeniente, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelModificarTenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelReporteModificarTeniente)
                                    .addComponent(labelModificarUnidades)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textModificarUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(43, 43, 43))))
        );
        panelModificarTenienteLayout.setVerticalGroup(
            panelModificarTenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarTenienteLayout.createSequentialGroup()
                .addComponent(panelModificarTeniente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(panelModificarTenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNameModificarTeniente)
                    .addComponent(labelReporteModificarTeniente))
                .addGap(12, 12, 12)
                .addGroup(panelModificarTenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelModificarTenienteLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(labelModificarUnidades)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textModificarUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelModificarTenienteLayout.createSequentialGroup()
                        .addComponent(textNombreModificarTeniente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelNivelModificarTeniente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textNivelModificarTeniente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelAccionModificarTeniente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textAccionModificarTeniente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(labelMisionModificarTeniente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(panelModificarTenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonResetModificarTeniente)
                    .addComponent(botonModificarTeniente)
                    .addComponent(botonEliminarTeniente))
                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelBuscadorModificarTeniente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelModificarTeniente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelModificarTeniente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panelBuscadorModificarTeniente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textBuscadorModificarTenienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreModificarTenienteActionPerformed

        int contador = 0;
        boolean encontrado = false;
        String buscador;
        buscador=textBuscadorModificarTeniente.getText();

        for (Teniente Teniente: listaTeniente) {

            if(buscador.equals(Teniente.id)){
        
                textNombreModificarTeniente.setText(Teniente.nombre);
                textNivelModificarTeniente.setText(Teniente.nivel);
                areaMisionModificarTeniente.setText(Teniente.mision);
                areaReporteModificarTeniente1.setText(Teniente.reporte);
                textAccionModificarTeniente.setText(accionTeniente.get(contador));
                textModificarUnidades.setText(Teniente.unidad);
            
                encontrado = true;
            }else{
                contador ++;
            
            }
        }
        if(encontrado == false){
            JOptionPane.showMessageDialog(null, "No se encontró el Teniente", "Información Teniente", JOptionPane.ERROR_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, "Teniente encontrado"+ "\n" + "Modifique los campos", "Modificar Teniente", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void botonModificarTenienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarTenienteActionPerformed
        ////////////////////
        //MODIFICARTeniente//
        ////////////////////

        //Variable para verificar si el Teniente fue encontrado
            
        //Dato que se compararan con la lista 
        String buscador;
        buscador=textBuscadorModificarTeniente.getText();

        int contador = 0;
        //Siclo para recorrer la lista
        //Si el Teniente no fue encontrado se muestra este mensaje

        for (Teniente Teniente : listaTeniente) {

            //Condicion para verificar si el Teniente existe comparando con los datos ingresados
            if(buscador.equals(Teniente.id)){
                    
                textBuscadorModificarTeniente.setText("");
                
                //Remplazo de datos
                
                Teniente.nombre = textNombreModificarTeniente.getText();
                Teniente.nivel=textNivelModificarTeniente.getText();

                    //do while para evitar ids repetidos
                    do {
                    
                    //Remplazamos el elemento de la posicion contador con su nueva mision,reprote y accion
                    Teniente.mision = areaMisionModificarTeniente.getText();                 
                    Teniente.reporte = areaReporteModificarTeniente1.getText();
                    Teniente.unidad = textModificarUnidades.getText();
                    String accion = textAccionModificarTeniente.getText();
                    accionTeniente.set(contador,accion);

                    JOptionPane.showMessageDialog(null, "Teniente Actualizado Con éxito", "Modificar Teniente", JOptionPane.INFORMATION_MESSAGE);
                    
                    //Mostrar la informacion del Teniente actualizada
                    JOptionPane.showMessageDialog(null, 
                    "Nombre: " + Teniente.nombre + "\n" +
                    "ID: " + Teniente.id + "\n" +
                    "Rango: " + Teniente.rango + "\n" + 
                    "Nivel: " + Teniente.nivel + "\n" +
                    "Mision: " + Teniente.mision  + "\n" +
                    "Unidades: " + Teniente.unidad + "\n" +
                    "Reporte: " + Teniente.reporte, "Modificar Teniente", JOptionPane.INFORMATION_MESSAGE);
                    System.out.println("FUNCIONA");
                    
                    
                    JOptionPane.showMessageDialog(null, "Acción: " + accionTeniente.get(contador), "Información Teniente", JOptionPane.INFORMATION_MESSAGE);

                    //Fin del siclo for
                    break;
                }while (true);{
                    contador++;//incrementamos el contador para que este en el mismo indice que el Teniente
                }
            }
        }
    }

    private void botonEliminarTenienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarTenienteActionPerformed
        
        int contador = 0;
        String buscador;
        buscador=textBuscadorModificarTeniente.getText();

        for (Teniente Teniente : listaTeniente) {

            if(buscador.equals(Teniente.id)){

                listaTeniente.remove(Teniente);
                accionTeniente.remove(contador);
                JOptionPane.showMessageDialog(null, "Soldado Eliminado Con Exito");
            }else{
                contador ++;

            }
        }

    }//GEN-LAST:event_botonEliminarTenienteActionPerformed
    
    private void botonResetModificarTenienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonResetModificarTenienteActionPerformed
        textBuscadorModificarTeniente.setText("");
        textNombreModificarTeniente.setText("");
        textNivelModificarTeniente.setText("");
        textAccionModificarTeniente.setText("");
        areaMisionModificarTeniente.setText("");
        areaReporteModificarTeniente1.setText("");
        textModificarUnidades.setText("");
    }//GEN-LAST:event_botonResetModificarTenienteActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarTeniente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarTeniente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarTeniente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarTeniente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarTeniente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaMisionModificarTeniente;
    private javax.swing.JTextArea areaReporteModificarTeniente1;
    private javax.swing.JButton botonEliminarTeniente;
    private javax.swing.JButton botonModificarTeniente;
    private javax.swing.JButton botonResetModificarTeniente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelAccionModificarTeniente;
    private javax.swing.JLabel labelMisionModificarTeniente;
    private javax.swing.JLabel labelModificarTeniente;
    private javax.swing.JLabel labelModificarUnidades;
    private javax.swing.JLabel labelNameModificarTeniente;
    private javax.swing.JLabel labelNivelModificarTeniente;
    private javax.swing.JLabel labelReporteModificarTeniente;
    private javax.swing.JPanel panelBuscadorModificarTeniente;
    private javax.swing.JPanel panelModificarTeniente;
    private javax.swing.JPanel panelModificarTeniente2;
    private javax.swing.JTextField textAccionModificarTeniente;
    private javax.swing.JTextField textBuscadorModificarTeniente;
    private javax.swing.JLabel textBuscarModificarTeniente;
    private javax.swing.JTextField textModificarUnidades;
    private javax.swing.JTextField textNivelModificarTeniente;
    private javax.swing.JTextField textNombreModificarTeniente;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrarInformacion() {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'mostrarInformacion'");
    }



    @Override
    public void asignarMision(String mision) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'asignarMision'");
    }

    @Override
    public void reportarEstado() {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'reportarEstado'");
    }

    @Override
    public void crearSoldado() {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'crearSoldado'");
    }

    @Override
    public void modificarSoldado() {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'modificarSoldado'");
    }
}
