/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//package com.mycompany.project;

/**
 *
 * @author josue
 */
public class CrearCapitan extends javax.swing.JFrame implements ActionListener, ItemListener, OperacionesMilitares{

    /**
     * Creates new form crearCapitan
     */
    public CrearCapitan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        panelCrearCapitan = new javax.swing.JPanel();
        labelNameCrearCapitan = new javax.swing.JLabel();
        textIDCrearCapitan = new javax.swing.JTextField();
        labelIDCrearCapitan = new javax.swing.JLabel();
        textNombreCrearCapitan = new javax.swing.JTextField();
        labelNivelCrearCapitan = new javax.swing.JLabel();
        textNivelCrearCapitan = new javax.swing.JTextField();
        labelReporteCrearCapitan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaReporteCrearCapitan = new javax.swing.JTextArea();
        labelMisionCrearCapitan = new javax.swing.JLabel();
        labelAccionCrearCapitan = new javax.swing.JLabel();
        textAccionCrearCapitan = new javax.swing.JTextField();
        panelCrearCapitan2 = new javax.swing.JPanel();
        labelCrearCapitan2 = new javax.swing.JLabel();
        labelEstrategia = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaMisionCrearCapitan = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaEstrategiaCrearCapitan = new javax.swing.JTextArea();
        botonCapitan = new javax.swing.JButton();
        botonResetCapitan1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelCrearCapitan.setBackground(new java.awt.Color(19, 71, 89));

        labelNameCrearCapitan.setForeground(new java.awt.Color(255, 255, 255));
        labelNameCrearCapitan.setText("Nombre");

        labelIDCrearCapitan.setForeground(new java.awt.Color(255, 255, 255));
        labelIDCrearCapitan.setText("ID");

        textNombreCrearCapitan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombreCrearCapitanActionPerformed(evt);
            }
        });

        labelNivelCrearCapitan.setForeground(new java.awt.Color(255, 255, 255));
        labelNivelCrearCapitan.setText("Nivel");

        labelReporteCrearCapitan.setForeground(new java.awt.Color(255, 255, 255));
        labelReporteCrearCapitan.setText("Reporte");

        areaReporteCrearCapitan.setColumns(20);
        areaReporteCrearCapitan.setRows(5);
        jScrollPane1.setViewportView(areaReporteCrearCapitan);

        labelMisionCrearCapitan.setForeground(new java.awt.Color(255, 255, 255));
        labelMisionCrearCapitan.setText("Misión");

        labelAccionCrearCapitan.setForeground(new java.awt.Color(255, 255, 255));
        labelAccionCrearCapitan.setText("Acción");

        panelCrearCapitan2.setBackground(new java.awt.Color(0, 153, 153));

        labelCrearCapitan2.setBackground(new java.awt.Color(0, 153, 153));
        labelCrearCapitan2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelCrearCapitan2.setForeground(new java.awt.Color(255, 255, 255));
        labelCrearCapitan2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCrearCapitan2.setText("Crear Capitan");

        javax.swing.GroupLayout panelCrearCapitan2Layout = new javax.swing.GroupLayout(panelCrearCapitan2);
        panelCrearCapitan2.setLayout(panelCrearCapitan2Layout);
        panelCrearCapitan2Layout.setHorizontalGroup(
            panelCrearCapitan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCrearCapitan2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCrearCapitan2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCrearCapitan2Layout.setVerticalGroup(
            panelCrearCapitan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearCapitan2Layout.createSequentialGroup()
                .addComponent(labelCrearCapitan2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        labelEstrategia.setForeground(new java.awt.Color(255, 255, 255));
        labelEstrategia.setText("Estrategia");

        areaMisionCrearCapitan.setColumns(20);
        areaMisionCrearCapitan.setRows(5);
        jScrollPane3.setViewportView(areaMisionCrearCapitan);

        areaEstrategiaCrearCapitan.setColumns(20);
        areaEstrategiaCrearCapitan.setRows(5);
        jScrollPane2.setViewportView(areaEstrategiaCrearCapitan);

        botonCapitan.setBackground(new java.awt.Color(0, 153, 153));
        botonCapitan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonCapitan.setText("Next");

        botonResetCapitan1.setBackground(new java.awt.Color(0, 153, 153));
        botonResetCapitan1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonResetCapitan1.setText("Reset");

        botonResetCapitan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonResetCapitan1ActionPerformed(evt);
            }
        });
        

        javax.swing.GroupLayout panelCrearCapitanLayout = new javax.swing.GroupLayout(panelCrearCapitan);
        panelCrearCapitan.setLayout(panelCrearCapitanLayout);
        panelCrearCapitanLayout.setHorizontalGroup(
            panelCrearCapitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCrearCapitan2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelCrearCapitanLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(panelCrearCapitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCrearCapitanLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelCrearCapitanLayout.createSequentialGroup()
                        .addComponent(labelMisionCrearCapitan)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCrearCapitanLayout.createSequentialGroup()
                        .addGroup(panelCrearCapitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelCrearCapitanLayout.createSequentialGroup()
                                .addComponent(botonResetCapitan1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonCapitan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCrearCapitanLayout.createSequentialGroup()
                                .addGroup(panelCrearCapitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textIDCrearCapitan, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textNombreCrearCapitan, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelIDCrearCapitan)
                                    .addComponent(labelNivelCrearCapitan)
                                    .addComponent(labelNameCrearCapitan)
                                    .addComponent(textNivelCrearCapitan, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelAccionCrearCapitan)
                                    .addComponent(textAccionCrearCapitan, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                                .addGroup(panelCrearCapitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelReporteCrearCapitan)
                                    .addComponent(labelEstrategia)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(43, 43, 43))))
        );
        panelCrearCapitanLayout.setVerticalGroup(
            panelCrearCapitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearCapitanLayout.createSequentialGroup()
                .addComponent(panelCrearCapitan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(panelCrearCapitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNameCrearCapitan)
                    .addComponent(labelReporteCrearCapitan))
                .addGroup(panelCrearCapitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCrearCapitanLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(textNombreCrearCapitan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelIDCrearCapitan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textIDCrearCapitan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCrearCapitanLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelCrearCapitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNivelCrearCapitan)
                    .addComponent(labelEstrategia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCrearCapitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCrearCapitanLayout.createSequentialGroup()
                        .addComponent(textNivelCrearCapitan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelAccionCrearCapitan)
                        .addGap(12, 12, 12)
                        .addComponent(textAccionCrearCapitan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelMisionCrearCapitan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(panelCrearCapitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCapitan)
                    .addComponent(botonResetCapitan1))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelCrearCapitan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelCrearCapitan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNombreCrearCapitanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreCrearCapitanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNombreCrearCapitanActionPerformed

    private void botonResetCapitan1ActionPerformed(java.awt.event.ActionEvent evt) {
        textNombreCrearCapitan.setText("");
        textIDCrearCapitan.setText("");
        textNivelCrearCapitan.setText("");
        textAccionCrearCapitan.setText("");
        areaMisionCrearCapitan.setText("");
        areaReporteCrearCapitan.setText("");
        areaEstrategiaCrearCapitan.setText("");
        
    }

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearCapitan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearCapitan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearCapitan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearCapitan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearCapitan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaEstrategiaCrearCapitan;
    private javax.swing.JTextArea areaMisionCrearCapitan;
    private javax.swing.JTextArea areaReporteCrearCapitan;
    private javax.swing.JButton botonCapitan;
    private javax.swing.JButton botonResetCapitan1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelAccionCrearCapitan;
    private javax.swing.JLabel labelCrearCapitan2;
    private javax.swing.JLabel labelEstrategia;
    private javax.swing.JLabel labelIDCrearCapitan;
    private javax.swing.JLabel labelMisionCrearCapitan;
    private javax.swing.JLabel labelNameCrearCapitan;
    private javax.swing.JLabel labelNivelCrearCapitan;
    private javax.swing.JLabel labelReporteCrearCapitan;
    private javax.swing.JPanel panelCrearCapitan;
    private javax.swing.JPanel panelCrearCapitan2;
    private javax.swing.JTextField textAccionCrearCapitan;
    private javax.swing.JTextField textIDCrearCapitan;
    private javax.swing.JTextField textNivelCrearCapitan;
    private javax.swing.JTextField textNombreCrearCapitan;
    // End of variables declaration//GEN-END:variables
    @Override
    public void crearSoldado() {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'crearSoldado'");
    }

    @Override
    public void mostrarInformacion() {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'mostrarInformacion'");
    }

    @Override
    public void modificarSoldado() {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'modificarSoldado'");
    }

    @Override
    public void asignarMision(String mision) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'asignarMision'");
    }

    @Override
    public void reportarEstado() {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'reportarEstado'");
    }
}
