import java.util.ArrayList;
import java.util.ArrayList;  
import java.util.List;

import javax.swing.JOptionPane;  
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
//import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//package com.mycompany.project;

/**
 *
 * @author josue
 */
public class CrearTeniente extends javax.swing.JFrame  implements ActionListener, ItemListener, OperacionesMilitares{
    static ArrayList<Teniente> listaTeniente = new ArrayList<>();

    /**
     * Creates new form CrearTeniente
     */
    public CrearTeniente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCrearTeniente = new javax.swing.JPanel();
        labelNameCrearTeniente = new javax.swing.JLabel();
        textIDCrearTeniente = new javax.swing.JTextField();
        labelIDCrearTeniente = new javax.swing.JLabel();
        textNombreCrearTeniente = new javax.swing.JTextField();
        labelNivelCrearTeniente = new javax.swing.JLabel();
        textNivelCrearTeniente = new javax.swing.JTextField();
        labelReporteCrearTeniente = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaMisionCrearTeniente = new javax.swing.JTextArea();
        labelMisionCrearTeniente = new javax.swing.JLabel();
        labelAccionCrearTeniente = new javax.swing.JLabel();
        textAccionCrearTeniente = new javax.swing.JTextField();
        panelCrearTeniente2 = new javax.swing.JPanel();
        labelCrearSoldado = new javax.swing.JLabel();
        labelUnidades = new javax.swing.JLabel();
        textUnidades = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaReporteCrearTeniente1 = new javax.swing.JTextArea();
        botonTeniente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelCrearTeniente.setBackground(new java.awt.Color(19, 71, 89));

        labelNameCrearTeniente.setForeground(new java.awt.Color(255, 255, 255));
        labelNameCrearTeniente.setText("Nombre");

        labelIDCrearTeniente.setForeground(new java.awt.Color(255, 255, 255));
        labelIDCrearTeniente.setText("ID");

        textNombreCrearTeniente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombreCrearTenienteActionPerformed(evt);
            }
        });

        labelNivelCrearTeniente.setForeground(new java.awt.Color(255, 255, 255));
        labelNivelCrearTeniente.setText("Nivel");

        labelReporteCrearTeniente.setForeground(new java.awt.Color(255, 255, 255));
        labelReporteCrearTeniente.setText("Reporte");

        areaMisionCrearTeniente.setColumns(20);
        areaMisionCrearTeniente.setRows(5);
        jScrollPane1.setViewportView(areaMisionCrearTeniente);

        labelMisionCrearTeniente.setForeground(new java.awt.Color(255, 255, 255));
        labelMisionCrearTeniente.setText("Misión");

        labelAccionCrearTeniente.setForeground(new java.awt.Color(255, 255, 255));
        labelAccionCrearTeniente.setText("Acción");

        panelCrearTeniente2.setBackground(new java.awt.Color(0, 153, 153));

        labelCrearSoldado.setBackground(new java.awt.Color(0, 153, 153));
        labelCrearSoldado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelCrearSoldado.setForeground(new java.awt.Color(255, 255, 255));
        labelCrearSoldado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCrearSoldado.setText("Crear Teniente");

        javax.swing.GroupLayout panelCrearTeniente2Layout = new javax.swing.GroupLayout(panelCrearTeniente2);
        panelCrearTeniente2.setLayout(panelCrearTeniente2Layout);
        panelCrearTeniente2Layout.setHorizontalGroup(
            panelCrearTeniente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCrearTeniente2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCrearSoldado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCrearTeniente2Layout.setVerticalGroup(
            panelCrearTeniente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearTeniente2Layout.createSequentialGroup()
                .addComponent(labelCrearSoldado, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        labelUnidades.setForeground(new java.awt.Color(255, 255, 255));
        labelUnidades.setText("Unidades de las que se hace cargo");

        areaReporteCrearTeniente1.setColumns(20);
        areaReporteCrearTeniente1.setRows(5);
        jScrollPane3.setViewportView(areaReporteCrearTeniente1);

        botonTeniente.setBackground(new java.awt.Color(0, 153, 153));
        botonTeniente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonTeniente.setText("Next");
        botonTeniente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTenienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCrearTenienteLayout = new javax.swing.GroupLayout(panelCrearTeniente);
        panelCrearTeniente.setLayout(panelCrearTenienteLayout);
        panelCrearTenienteLayout.setHorizontalGroup(
            panelCrearTenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCrearTeniente2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelCrearTenienteLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(panelCrearTenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCrearTenienteLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelCrearTenienteLayout.createSequentialGroup()
                        .addComponent(labelMisionCrearTeniente)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelCrearTenienteLayout.createSequentialGroup()
                        .addGroup(panelCrearTenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textIDCrearTeniente, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textNombreCrearTeniente, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelIDCrearTeniente)
                            .addComponent(labelNivelCrearTeniente)
                            .addComponent(labelNameCrearTeniente)
                            .addComponent(textNivelCrearTeniente, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelAccionCrearTeniente)
                            .addComponent(textAccionCrearTeniente, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelCrearTenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelReporteCrearTeniente)
                            .addComponent(labelUnidades)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCrearTenienteLayout.createSequentialGroup()
                .addContainerGap(227, Short.MAX_VALUE)
                .addComponent(botonTeniente, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(227, 227, 227))
        );
        panelCrearTenienteLayout.setVerticalGroup(
            panelCrearTenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearTenienteLayout.createSequentialGroup()
                .addComponent(panelCrearTeniente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(panelCrearTenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNameCrearTeniente)
                    .addComponent(labelReporteCrearTeniente))
                .addGap(12, 12, 12)
                .addGroup(panelCrearTenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCrearTenienteLayout.createSequentialGroup()
                        .addComponent(textNombreCrearTeniente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelIDCrearTeniente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textIDCrearTeniente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCrearTenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNivelCrearTeniente)
                    .addComponent(labelUnidades))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCrearTenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNivelCrearTeniente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelAccionCrearTeniente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textAccionCrearTeniente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelMisionCrearTeniente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonTeniente)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCrearTeniente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCrearTeniente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNombreCrearTenienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreCrearTenienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNombreCrearTenienteActionPerformed
    @SuppressWarnings("unused")
    private void botonTenienteActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String nombre = textNombreCrearTeniente.getText();
        String id = textIDCrearTeniente.getText();
        String nivel = textNivelCrearTeniente.getText();
        String unidades = textUnidades.getText();
        String accion = textAccionCrearTeniente.getText();
        String mision = areaMisionCrearTeniente.getText();
        String reporte = areaReporteCrearTeniente1.getText();

        if (!nombre.isEmpty() && !id.isEmpty() && !accion.isEmpty()) {
            listaTeniente.add(new Teniente());
            JOptionPane.showMessageDialog(this, "Soldado creado con éxito!");
            
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.");
        }
        
       
        
    }
    


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearTeniente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearTeniente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearTeniente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearTeniente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearTeniente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaMisionCrearTeniente;
    private javax.swing.JTextArea areaReporteCrearTeniente1;
    private javax.swing.JButton botonTeniente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelAccionCrearTeniente;
    private javax.swing.JLabel labelCrearSoldado;
    private javax.swing.JLabel labelIDCrearTeniente;
    private javax.swing.JLabel labelMisionCrearTeniente;
    private javax.swing.JLabel labelNameCrearTeniente;
    private javax.swing.JLabel labelNivelCrearTeniente;
    private javax.swing.JLabel labelReporteCrearTeniente;
    private javax.swing.JLabel labelUnidades;
    private javax.swing.JPanel panelCrearTeniente;
    private javax.swing.JPanel panelCrearTeniente2;
    private javax.swing.JTextField textAccionCrearTeniente;
    private javax.swing.JTextField textIDCrearTeniente;
    private javax.swing.JTextField textNivelCrearTeniente;
    private javax.swing.JTextField textNombreCrearTeniente;
    private javax.swing.JTextField textUnidades;
    // End of variables declaration//GEN-END:variables
    @Override
    public void itemStateChanged(ItemEvent e) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'itemStateChanged'");
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'actionPerformed'");
    }

    @Override
    public void crearSoldado() {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'crearSoldado'");
    }

    @Override
    public void mostrarInformacion() {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'mostrarInformacion'");
    }

    @Override
    public void modificarSoldado() {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'modificarSoldado'");
    }

    @Override
    public void asignarMision(String mision) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'asignarMision'");
    }

    @Override
    public void reportarEstado() {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'reportarEstado'");
    }
}
