/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//package com.mycompany.project;

/**
 *
 * @author josue
 */
public class ModificarTeniente extends javax.swing.JFrame {

    /**
     * Creates new form CrearTeniente
     */
    public ModificarTeniente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelModificarTeniente = new javax.swing.JPanel();
        labelNameModificarTeniente = new javax.swing.JLabel();
        textIDModificarTeniente = new javax.swing.JTextField();
        labelIDModificarTeniente = new javax.swing.JLabel();
        textIDModificarTeniente.setEditable(false);
        textNombreModificarTeniente = new javax.swing.JTextField();
        labelNivelModificarTeniente = new javax.swing.JLabel();
        textNivelModificarTeniente = new javax.swing.JTextField();
        labelReporteModificarTeniente = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaMisionModificarTeniente = new javax.swing.JTextArea();
        labelMisionModificarTeniente = new javax.swing.JLabel();
        labelAccionModificarTeniente = new javax.swing.JLabel();
        textAccionModificarTeniente = new javax.swing.JTextField();
        panelModificarTeniente2 = new javax.swing.JPanel();
        labelModificarSoldado = new javax.swing.JLabel();
        labelModificarUnidades = new javax.swing.JLabel();
        textModificarUnidades = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaReporteModificarTeniente1 = new javax.swing.JTextArea();
        botonModificarTeniente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelModificarTeniente.setBackground(new java.awt.Color(19, 71, 89));

        labelNameModificarTeniente.setForeground(new java.awt.Color(255, 255, 255));
        labelNameModificarTeniente.setText("Nombre");

        labelIDModificarTeniente.setForeground(new java.awt.Color(255, 255, 255));
        labelIDModificarTeniente.setText("ID");

        textNombreModificarTeniente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombreModificarTenienteActionPerformed(evt);
            }
        });

        labelNivelModificarTeniente.setForeground(new java.awt.Color(255, 255, 255));
        labelNivelModificarTeniente.setText("Nivel");

        labelReporteModificarTeniente.setForeground(new java.awt.Color(255, 255, 255));
        labelReporteModificarTeniente.setText("Reporte");

        areaMisionModificarTeniente.setColumns(20);
        areaMisionModificarTeniente.setRows(5);
        jScrollPane1.setViewportView(areaMisionModificarTeniente);

        labelMisionModificarTeniente.setForeground(new java.awt.Color(255, 255, 255));
        labelMisionModificarTeniente.setText("Misión");

        labelAccionModificarTeniente.setForeground(new java.awt.Color(255, 255, 255));
        labelAccionModificarTeniente.setText("Acción");

        panelModificarTeniente2.setBackground(new java.awt.Color(0, 153, 153));

        labelModificarSoldado.setBackground(new java.awt.Color(0, 153, 153));
        labelModificarSoldado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelModificarSoldado.setForeground(new java.awt.Color(255, 255, 255));
        labelModificarSoldado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelModificarSoldado.setText("Modificar Teniente");

        javax.swing.GroupLayout panelModificarTeniente2Layout = new javax.swing.GroupLayout(panelModificarTeniente2);
        panelModificarTeniente2.setLayout(panelModificarTeniente2Layout);
        panelModificarTeniente2Layout.setHorizontalGroup(
            panelModificarTeniente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelModificarTeniente2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelModificarSoldado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelModificarTeniente2Layout.setVerticalGroup(
            panelModificarTeniente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarTeniente2Layout.createSequentialGroup()
                .addComponent(labelModificarSoldado, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        labelModificarUnidades.setForeground(new java.awt.Color(255, 255, 255));
        labelModificarUnidades.setText("Unidades de las que se hace cargo");

        areaReporteModificarTeniente1.setColumns(20);
        areaReporteModificarTeniente1.setRows(5);
        jScrollPane3.setViewportView(areaReporteModificarTeniente1);

        botonModificarTeniente.setBackground(new java.awt.Color(0, 153, 153));
        botonModificarTeniente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonModificarTeniente.setText("Next");

        javax.swing.GroupLayout panelModificarTenienteLayout = new javax.swing.GroupLayout(panelModificarTeniente);
        panelModificarTeniente.setLayout(panelModificarTenienteLayout);
        panelModificarTenienteLayout.setHorizontalGroup(
            panelModificarTenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelModificarTeniente2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelModificarTenienteLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(panelModificarTenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelModificarTenienteLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelModificarTenienteLayout.createSequentialGroup()
                        .addComponent(labelMisionModificarTeniente)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelModificarTenienteLayout.createSequentialGroup()
                        .addGroup(panelModificarTenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textIDModificarTeniente, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textNombreModificarTeniente, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelIDModificarTeniente)
                            .addComponent(labelNivelModificarTeniente)
                            .addComponent(labelNameModificarTeniente)
                            .addComponent(textNivelModificarTeniente, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelAccionModificarTeniente)
                            .addComponent(textAccionModificarTeniente, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelModificarTenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelReporteModificarTeniente)
                            .addComponent(labelModificarUnidades)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textModificarUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelModificarTenienteLayout.createSequentialGroup()
                .addContainerGap(227, Short.MAX_VALUE)
                .addComponent(botonModificarTeniente, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(227, 227, 227))
        );
        panelModificarTenienteLayout.setVerticalGroup(
            panelModificarTenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarTenienteLayout.createSequentialGroup()
                .addComponent(panelModificarTeniente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(panelModificarTenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNameModificarTeniente)
                    .addComponent(labelReporteModificarTeniente))
                .addGap(12, 12, 12)
                .addGroup(panelModificarTenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelModificarTenienteLayout.createSequentialGroup()
                        .addComponent(textNombreModificarTeniente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelIDModificarTeniente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textIDModificarTeniente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelModificarTenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNivelModificarTeniente)
                    .addComponent(labelModificarUnidades))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelModificarTenienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNivelModificarTeniente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textModificarUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelAccionModificarTeniente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textAccionModificarTeniente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelMisionModificarTeniente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonModificarTeniente)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelModificarTeniente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelModificarTeniente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNombreModificarTenienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreModificarTenienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNombreModificarTenienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarTeniente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarTeniente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarTeniente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarTeniente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarTeniente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaMisionModificarTeniente;
    private javax.swing.JTextArea areaReporteModificarTeniente1;
    private javax.swing.JButton botonModificarTeniente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelAccionModificarTeniente;
    private javax.swing.JLabel labelIDModificarTeniente;
    private javax.swing.JLabel labelMisionModificarTeniente;
    private javax.swing.JLabel labelModificarSoldado;
    private javax.swing.JLabel labelModificarUnidades;
    private javax.swing.JLabel labelNameModificarTeniente;
    private javax.swing.JLabel labelNivelModificarTeniente;
    private javax.swing.JLabel labelReporteModificarTeniente;
    private javax.swing.JPanel panelModificarTeniente;
    private javax.swing.JPanel panelModificarTeniente2;
    private javax.swing.JTextField textAccionModificarTeniente;
    private javax.swing.JTextField textIDModificarTeniente;
    private javax.swing.JTextField textModificarUnidades;
    private javax.swing.JTextField textNivelModificarTeniente;
    private javax.swing.JTextField textNombreModificarTeniente;
    // End of variables declaration//GEN-END:variables
}
