/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//package com.mycompany.project;

import java.awt.event.ActionEvent;

import javax.swing.JOptionPane;

import org.w3c.dom.Text;

/**
 *
 * @author josue
 */
public class MostrarSoldadoRaso extends javax.swing.JFrame implements ActionListener, ItemListener, OperacionesMilitares{

    /**
     * Creates new form MostrarSoldadoRaso
     */
    public MostrarSoldadoRaso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMostrarSoldado = new javax.swing.JPanel();
        labelNameMostrarSoldado = new javax.swing.JLabel();
        textIDMostrarSoldado = new javax.swing.JTextField();
        labelIDMostrarSoldado = new javax.swing.JLabel();
        textNombreMostrarSoldado = new javax.swing.JTextField();
        labelNivelMostrarSoldado = new javax.swing.JLabel();
        textNivelMostrarSoldado = new javax.swing.JTextField();
        labelReporteMostrarSoldado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaMisionMostrarSoldadoRaso = new javax.swing.JTextArea();
        labelMisionMostrarSoldado = new javax.swing.JLabel();
        labelAccionMostrarSoldado = new javax.swing.JLabel();
        textAccionMostrarSoldado = new javax.swing.JTextField();
        panelMostrarSoldado2 = new javax.swing.JPanel();
        labelMostrarSoldado = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaReporteMostrarSoldado = new javax.swing.JTextArea();
        botonMostrarSoldado = new javax.swing.JButton();
        botonResetMostrarSoldado = new javax.swing.JButton();
        panelBuscadorSoldadoRaso = new javax.swing.JPanel();
        textBuscadorSoldadoRaso = new javax.swing.JTextField();
        textBuscarSoldadoRaso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelMostrarSoldado.setBackground(new java.awt.Color(19, 71, 89));
        panelMostrarSoldado.setPreferredSize(new java.awt.Dimension(544, 593));

        labelNameMostrarSoldado.setForeground(new java.awt.Color(255, 255, 255));
        labelNameMostrarSoldado.setText("Nombre");

        textIDMostrarSoldado.setEditable(false);

        labelIDMostrarSoldado.setForeground(new java.awt.Color(255, 255, 255));
        labelIDMostrarSoldado.setText("ID");

        textNombreMostrarSoldado.setEditable(false);
        textNombreMostrarSoldado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombreMostrarSoldadoActionPerformed(evt);
            }
        });

        labelNivelMostrarSoldado.setForeground(new java.awt.Color(255, 255, 255));
        labelNivelMostrarSoldado.setText("Nivel");

        textNivelMostrarSoldado.setEditable(false);

        labelReporteMostrarSoldado.setForeground(new java.awt.Color(255, 255, 255));
        labelReporteMostrarSoldado.setText("Reporte");

        areaMisionMostrarSoldadoRaso.setEditable(false);
        areaMisionMostrarSoldadoRaso.setColumns(20);
        areaMisionMostrarSoldadoRaso.setRows(5);
        jScrollPane1.setViewportView(areaMisionMostrarSoldadoRaso);

        labelMisionMostrarSoldado.setForeground(new java.awt.Color(255, 255, 255));
        labelMisionMostrarSoldado.setText("Misión");

        labelAccionMostrarSoldado.setForeground(new java.awt.Color(255, 255, 255));
        labelAccionMostrarSoldado.setText("Acción");

        textAccionMostrarSoldado.setEditable(false);

        panelMostrarSoldado2.setBackground(new java.awt.Color(0, 153, 153));

        labelMostrarSoldado.setBackground(new java.awt.Color(0, 153, 153));
        labelMostrarSoldado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelMostrarSoldado.setForeground(new java.awt.Color(255, 255, 255));
        labelMostrarSoldado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMostrarSoldado.setText("Mostrar Soldado Raso");

        javax.swing.GroupLayout panelMostrarSoldado2Layout = new javax.swing.GroupLayout(panelMostrarSoldado2);
        panelMostrarSoldado2.setLayout(panelMostrarSoldado2Layout);
        panelMostrarSoldado2Layout.setHorizontalGroup(
            panelMostrarSoldado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMostrarSoldado2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMostrarSoldado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelMostrarSoldado2Layout.setVerticalGroup(
            panelMostrarSoldado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMostrarSoldado2Layout.createSequentialGroup()
                .addComponent(labelMostrarSoldado, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        areaReporteMostrarSoldado.setEditable(false);
        areaReporteMostrarSoldado.setColumns(20);
        areaReporteMostrarSoldado.setRows(5);
        jScrollPane3.setViewportView(areaReporteMostrarSoldado);

        botonMostrarSoldado.setBackground(new java.awt.Color(0, 153, 153));
        botonMostrarSoldado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonMostrarSoldado.setText("Mostrar");
        botonMostrarSoldado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarSoldadoActionPerformed(evt);
            }

        });

        botonResetMostrarSoldado.setBackground(new java.awt.Color(0, 153, 153));
        botonResetMostrarSoldado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonResetMostrarSoldado.setText("Reset");
        botonResetMostrarSoldado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonResetMostrarSoldadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMostrarSoldadoLayout = new javax.swing.GroupLayout(panelMostrarSoldado);
        panelMostrarSoldado.setLayout(panelMostrarSoldadoLayout);
        panelMostrarSoldadoLayout.setHorizontalGroup(
            panelMostrarSoldadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMostrarSoldado2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelMostrarSoldadoLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(panelMostrarSoldadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMostrarSoldadoLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelMostrarSoldadoLayout.createSequentialGroup()
                        .addComponent(labelMisionMostrarSoldado)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMostrarSoldadoLayout.createSequentialGroup()
                        .addGroup(panelMostrarSoldadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelMostrarSoldadoLayout.createSequentialGroup()
                                .addComponent(botonResetMostrarSoldado, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonMostrarSoldado, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelMostrarSoldadoLayout.createSequentialGroup()
                                .addGroup(panelMostrarSoldadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textIDMostrarSoldado, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textNombreMostrarSoldado, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelIDMostrarSoldado)
                                    .addComponent(labelNivelMostrarSoldado)
                                    .addComponent(labelNameMostrarSoldado)
                                    .addComponent(textNivelMostrarSoldado, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelAccionMostrarSoldado)
                                    .addComponent(textAccionMostrarSoldado, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                                .addGroup(panelMostrarSoldadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelReporteMostrarSoldado)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(43, 43, 43))))
        );
        panelMostrarSoldadoLayout.setVerticalGroup(
            panelMostrarSoldadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMostrarSoldadoLayout.createSequentialGroup()
                .addComponent(panelMostrarSoldado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(panelMostrarSoldadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNameMostrarSoldado)
                    .addComponent(labelReporteMostrarSoldado))
                .addGap(12, 12, 12)
                .addGroup(panelMostrarSoldadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMostrarSoldadoLayout.createSequentialGroup()
                        .addComponent(textNombreMostrarSoldado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelIDMostrarSoldado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textIDMostrarSoldado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelNivelMostrarSoldado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textNivelMostrarSoldado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelAccionMostrarSoldado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textAccionMostrarSoldado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelMisionMostrarSoldado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(panelMostrarSoldadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonMostrarSoldado)
                    .addComponent(botonResetMostrarSoldado))
                .addGap(41, 41, 41))
        );

        panelBuscadorSoldadoRaso.setBackground(new java.awt.Color(0, 153, 153));

        textBuscadorSoldadoRaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBuscadorSoldadoRasoActionPerformed(evt);
            }
        });

        textBuscarSoldadoRaso.setForeground(new java.awt.Color(255, 255, 255));
        textBuscarSoldadoRaso.setText("Buscar ID");

        javax.swing.GroupLayout panelBuscadorSoldadoRasoLayout = new javax.swing.GroupLayout(panelBuscadorSoldadoRaso);
        panelBuscadorSoldadoRaso.setLayout(panelBuscadorSoldadoRasoLayout);
        panelBuscadorSoldadoRasoLayout.setHorizontalGroup(
            panelBuscadorSoldadoRasoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBuscadorSoldadoRasoLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(panelBuscadorSoldadoRasoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textBuscarSoldadoRaso)
                    .addComponent(textBuscadorSoldadoRaso, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        panelBuscadorSoldadoRasoLayout.setVerticalGroup(
            panelBuscadorSoldadoRasoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscadorSoldadoRasoLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(textBuscarSoldadoRaso)
                .addGap(18, 18, 18)
                .addComponent(textBuscadorSoldadoRaso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelBuscadorSoldadoRaso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMostrarSoldado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBuscadorSoldadoRaso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelMostrarSoldado, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNombreMostrarSoldadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreMostrarSoldadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNombreMostrarSoldadoAct ionPerformed

    private void botonResetMostrarSoldadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonResetMostrarSoldadoActionPerformed
        
        textNombreMostrarSoldado.setText("");
        textIDMostrarSoldado.setText("");
        textNivelMostrarSoldado.setText("");
        textAccionMostrarSoldado.setText("");
        areaMisionMostrarSoldadoRaso.setText("");
        areaReporteMostrarSoldado.setText("");

    }

    private void textBuscadorSoldadoRasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBuscadorSoldadoRasoActionPerformed
        
    }//GEN-LAST:event_textBuscadorSoldadoRasoActionPerformed

    private void botonMostrarSoldadoActionPerformed(ActionEvent evt) {

        String buscador;

        buscador=textBuscadorSoldadoRaso.getText();

        System.out.println(buscador);

        textBuscadorSoldadoRaso.setText("");

        //////////////////////
        //MOSTRARINFORMACION//
        //////////////////////

            Boolean encontrado = false;
            int contador = 0;
            //Siclo para recorrer la lista
            for (SoldadoRaso soldado : listaSoldadoRaso) {

                System.out.println(listaSoldadoRaso.size());
                //Condicion para verificar si el soldado existe comparando con los datos ingresados
                if(buscador.equals(soldado.id)){
                    
                    
                    //Si se cumple muestra lo siguiente
                    textNombreMostrarSoldado.setText(soldado.nombre);
                    textIDMostrarSoldado.setText(soldado.id);
                    textNivelMostrarSoldado.setText(soldado.nivel);
                    textAccionMostrarSoldado.setText(accionSoldadoRaso.get(contador));
                    areaMisionMostrarSoldadoRaso.setText(soldado.mision);
                    areaReporteMostrarSoldado.setText(soldado.reporte);

                    System.out.println("x");

                    //Si el soldado fue encontrado la varieable se actualiza
                    encontrado = true;
                    break;
                }else{
                    contador ++;
                }
            }
            
            //Si el soldado no fue encontrado se muestra este mensaje
            if (encontrado == false) {
                JOptionPane.showMessageDialog(null, "No se encontró el soldado", "Información Soldado", JOptionPane.ERROR_MESSAGE);
            }
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarSoldadoRaso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarSoldadoRaso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarSoldadoRaso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarSoldadoRaso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarSoldadoRaso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaMisionMostrarSoldadoRaso;
    private javax.swing.JTextArea areaReporteMostrarSoldado;
    private javax.swing.JButton botonMostrarSoldado;
    private javax.swing.JButton botonResetMostrarSoldado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelAccionMostrarSoldado;
    private javax.swing.JLabel labelIDMostrarSoldado;
    private javax.swing.JLabel labelMisionMostrarSoldado;
    private javax.swing.JLabel labelMostrarSoldado;
    private javax.swing.JLabel labelNameMostrarSoldado;
    private javax.swing.JLabel labelNivelMostrarSoldado;
    private javax.swing.JLabel labelReporteMostrarSoldado;
    private javax.swing.JPanel panelBuscadorSoldadoRaso;
    private javax.swing.JPanel panelMostrarSoldado;
    private javax.swing.JPanel panelMostrarSoldado2;
    private javax.swing.JTextField textAccionMostrarSoldado;
    private javax.swing.JTextField textBuscadorSoldadoRaso;
    private javax.swing.JLabel textBuscarSoldadoRaso;
    private javax.swing.JTextField textIDMostrarSoldado;
    private javax.swing.JTextField textNivelMostrarSoldado;
    private javax.swing.JTextField textNombreMostrarSoldado;
    // End of variables declaration//GEN-END:variables
    @Override
    public void crearSoldado() {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'crearSoldado'");
    }

    @Override
    public void mostrarInformacion() {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'mostrarInformacion'");
    }

    @Override
    public void modificarSoldado() {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'modificarSoldado'");
    }

    @Override
    public void asignarMision(String mision) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'asignarMision'");
    }

    @Override
    public void reportarEstado() {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'reportarEstado'");
    }
}
